---

- name: Install Hashicorp Repo
  kubernetes.core.helm_repository:
    name: hashicorp
    repo_url: https://helm.releases.hashicorp.com

- name: Install vault helm chart
  kubernetes.core.helm:
    name: vault
    chart_ref: hashicorp/vault
    release_namespace: default
